<Router>
<div>
<nav>
<ul>
<li><Link to="/">Home</Link></li>
<li><Link to="/">Home</Link></li>

<li><Link to="/About">about</Link></li>
<li><Link to="/contact">contact</Link></li>

</ul>
</nav>

<Routes>
<Route path="/" element={<Home />}/>
<Route path="/" element={<Home />}/>
<Route path="/" element={<Home />}/>
<Route path="/about" element={<about />}/>
<Route path="/contact" element={<contact />}/>
</routes>
</div>
</router>
